import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';

const _sampleRate = 44100;
const _channels = 2;
const _bitsPerSample = 16;
const _generatorVersion = '1';

Future<void> main() async {
  final compressed = await generateTestMedia();
  stdout.writeln('compressed formats: ${compressed['status']}');
}

typedef FfmpegProcessRunner =
    Future<ProcessResult> Function(
      String executable,
      List<String> arguments, {
      bool runInShell,
    });

Future<Map<String, String>> generateTestMedia({
  Directory? outputDirectory,
  FfmpegProcessRunner? processRunner,
}) async {
  final output = outputDirectory ?? Directory('test_media/generated');
  await output.create(recursive: true);

  final files = <_Fixture>[
    _Fixture(
      'tone-440hz.wav',
      'real decoding and progress verification',
      5000,
      _toneSamples(durationMs: 5000, frequency: 440),
    ),
    _Fixture(
      'short-tone.wav',
      'completion event verification',
      1000,
      _toneSamples(durationMs: 1000, frequency: 660),
    ),
    _Fixture(
      'silence.wav',
      'silent valid PCM input',
      1000,
      _silenceSamples(durationMs: 1000),
    ),
    _Fixture(
      'stereo-left-right.wav',
      'manual channel-output confirmation',
      2000,
      _stereoSamples(durationMs: 2000),
    ),
  ];

  for (final fixture in files) {
    await File(
      '${output.path}${Platform.pathSeparator}${fixture.name}',
    ).writeAsBytes(_wav(fixture.samples), flush: true);
  }

  final tone = File('${output.path}${Platform.pathSeparator}tone-440hz.wav');
  final truncated = File(
    '${output.path}${Platform.pathSeparator}truncated.wav',
  );
  final toneBytes = await tone.readAsBytes();
  await truncated.writeAsBytes(toneBytes.sublist(0, 4096), flush: true);
  final random = File(
    '${output.path}${Platform.pathSeparator}random-bytes.bin',
  );
  await random.writeAsBytes(_deterministicBytes(1024), flush: true);

  final manifestFiles = <Map<String, Object?>>[];
  for (final fixture in files) {
    manifestFiles.add(
      await _describe(
        File('${output.path}${Platform.pathSeparator}${fixture.name}'),
        fixture.purpose,
        durationMs: fixture.durationMs,
      ),
    );
  }
  manifestFiles
    ..add(await _describe(truncated, 'intentionally truncated WAV input'))
    ..add(await _describe(random, 'deterministic non-media input'));

  final compressed = await _tryFfmpeg(
    output,
    tone,
    processRunner: processRunner,
  );
  await File(
    '${output.path}${Platform.pathSeparator}manifest.json',
  ).writeAsString(
    const JsonEncoder.withIndent('  ').convert({
      'generatorVersion': _generatorVersion,
      'signalLicense': 'Generated by project code; no third-party music.',
      'files': manifestFiles,
      'optionalCompressedDerivatives': const [
        'tone.mp3',
        'tone.flac',
        'tone.m4a',
        'tone.ogg',
        'tone.opus',
      ],
    }),
    flush: true,
  );

  for (final entry in manifestFiles) {
    stdout.writeln('${entry['name']} ${entry['sha256']}');
  }
  return compressed;
}

final class _Fixture {
  const _Fixture(this.name, this.purpose, this.durationMs, this.samples);
  final String name;
  final String purpose;
  final int durationMs;
  final Int16List samples;
}

Int16List _toneSamples({required int durationMs, required double frequency}) {
  final frames = _sampleRate * durationMs ~/ 1000;
  final data = Int16List(frames * _channels);
  for (var frame = 0; frame < frames; frame++) {
    final sample = (sin(2 * pi * frequency * frame / _sampleRate) * 10000)
        .round();
    data[frame * 2] = sample;
    data[frame * 2 + 1] = sample;
  }
  return data;
}

Int16List _silenceSamples({required int durationMs}) =>
    Int16List(_sampleRate * durationMs ~/ 1000 * _channels);

Int16List _stereoSamples({required int durationMs}) {
  final frames = _sampleRate * durationMs ~/ 1000;
  final data = Int16List(frames * _channels);
  for (var frame = 0; frame < frames; frame++) {
    final sample = (sin(2 * pi * 440 * frame / _sampleRate) * 10000).round();
    if (frame < frames ~/ 2) {
      data[frame * 2] = sample;
    } else {
      data[frame * 2 + 1] = sample;
    }
  }
  return data;
}

Uint8List _wav(Int16List samples) {
  final dataLength = samples.length * 2;
  final bytes = BytesBuilder(copy: false);
  void writeAscii(String value) => bytes.add(ascii.encode(value));
  void u16(int value) => bytes.add([value & 0xff, value >> 8 & 0xff]);
  void u32(int value) => bytes.add([
    value & 0xff,
    value >> 8 & 0xff,
    value >> 16 & 0xff,
    value >> 24 & 0xff,
  ]);
  writeAscii('RIFF');
  u32(36 + dataLength);
  writeAscii('WAVEfmt ');
  u32(16);
  u16(1);
  u16(_channels);
  u32(_sampleRate);
  u32(_sampleRate * _channels * _bitsPerSample ~/ 8);
  u16(_channels * _bitsPerSample ~/ 8);
  u16(_bitsPerSample);
  writeAscii('data');
  u32(dataLength);
  bytes.add(samples.buffer.asUint8List());
  return bytes.toBytes();
}

Uint8List _deterministicBytes(int length) {
  var state = 0x5eed1234;
  final bytes = Uint8List(length);
  for (var index = 0; index < length; index++) {
    state = (1664525 * state + 1013904223) & 0xffffffff;
    bytes[index] = state >> 24;
  }
  return bytes;
}

Future<Map<String, Object?>> _describe(
  File file,
  String purpose, {
  int? durationMs,
}) async {
  final result = <String, Object?>{
    'name': file.uri.pathSegments.last,
    'purpose': purpose,
    'sha256': sha256.convert(await file.readAsBytes()).toString(),
  };
  if (durationMs == null) return result;
  return {
    ...result,
    'sampleRate': _sampleRate,
    'channels': _channels,
    'durationMs': durationMs,
  };
}

Future<Map<String, String>> _tryFfmpeg(
  Directory output,
  File tone, {
  FfmpegProcessRunner? processRunner,
}) async {
  final runner = processRunner ?? _runProcess;
  ProcessResult check;

  try {
    check = await runner('ffmpeg', const [
      '-version',
    ], runInShell: Platform.isWindows);
  } on ProcessException catch (error) {
    return {
      'status': 'SKIPPED',
      'reason': 'ffmpeg unavailable: ${error.message}',
    };
  }

  if (check.exitCode != 0) {
    return {'status': 'SKIPPED', 'reason': 'ffmpeg unavailable'};
  }
  final formats = {
    'mp3': 'libmp3lame',
    'flac': 'flac',
    'm4a': 'aac',
    'ogg': 'libvorbis',
    'opus': 'libopus',
  };
  for (final entry in formats.entries) {
    final destination =
        '${output.path}${Platform.pathSeparator}tone.${entry.key}';
    ProcessResult result;

    try {
      result = await runner('ffmpeg', [
        '-y',
        '-i',
        tone.path,
        '-metadata',
        'title=MpvPlay Fixture Song',
        '-metadata',
        'artist=MpvPlay Fixture Artist',
        '-metadata',
        'album=MpvPlay Fixture Album',
        '-metadata',
        'genre=Test',
        '-c:a',
        entry.value,
        destination,
      ], runInShell: Platform.isWindows);
    } on ProcessException catch (error) {
      return {
        'status': 'SKIPPED',
        'reason': 'ffmpeg execution failed: ${error.message}',
      };
    }

    if (result.exitCode != 0) {
      return {
        'status': 'SKIPPED',
        'reason': 'ffmpeg codec ${entry.value} unavailable',
      };
    }
  }
  return {'status': 'GENERATED'};
}

Future<ProcessResult> _runProcess(
  String executable,
  List<String> arguments, {
  bool runInShell = false,
}) => Process.run(executable, arguments, runInShell: runInShell);
