// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    trackSearchFts,
    libraryRoots,
    scanRuns,
    mediaFiles,
    artworkAssets,
    artists,
    albums,
    tracks,
    trackArtists,
    genres,
    trackGenres,
    favoriteTracks,
    userPlaylists,
    userPlaylistItems,
    mediaFilesRootAvailability,
    mediaFilesRootLastSeenGeneration,
    mediaFilesPlatformFileId,
    mediaFilesQuickFingerprint,
    mediaFilesContentHash,
    artistsSortName,
    artistsName,
    albumsSortTitle,
    albumsAlbumArtistId,
    albumsArtworkId,
    tracksAlbumId,
    tracksSortTitle,
    tracksTitle,
    tracksArtworkId,
    trackArtistsArtistRolePosition,
    trackArtistsTrackPosition,
    trackGenresGenreId,
    trackGenresTrackPosition,
    favoriteTracksCreatedAt,
    userPlaylistsUpdatedAt,
    userPlaylistItemsPlaylistPosition,
  ];
  late final Shape0 trackSearchFts = Shape0(
    source: i0.VersionedVirtualTable(
      entityName: 'track_search_fts',
      moduleAndArgs:
          'fts5(track_public_id UNINDEXED, title, artist, album, file_name, tokenize = \'trigram\')',
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 libraryRoots = Shape1(
    source: i0.VersionedTable(
      entityName: 'library_roots',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'UNIQUE(source_type, locator_key)',
        'CHECK(source_type = \'windowsDirectory\')',
        'CHECK(scan_generation >= 0)',
      ],
      columns: [
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 scanRuns = Shape2(
    source: i0.VersionedTable(
      entityName: 'scan_runs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'UNIQUE(root_id, generation)',
        'CHECK(generation >= 0)',
        'CHECK(status IN (\'queued\', \'enumerating\', \'processing\', \'committing\', \'finalizing\', \'completed\', \'completedWithIssues\', \'cancelled\', \'failed\'))',
        'CHECK(discovered_count >= 0)',
        'CHECK(unchanged_count >= 0)',
        'CHECK(parsed_count >= 0)',
        'CHECK(inserted_count >= 0)',
        'CHECK(updated_count >= 0)',
        'CHECK(missing_count >= 0)',
        'CHECK(failed_count >= 0)',
      ],
      columns: [
        _column_5,
        _column_6,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 mediaFiles = Shape3(
    source: i0.VersionedTable(
      entityName: 'media_files',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'UNIQUE(root_id, locator_key)',
        'CHECK(size_bytes >= 0)',
        'CHECK(last_seen_generation >= 0)',
        'CHECK(availability_state IN (\'available\', \'missing\', \'unreadable\'))',
        'CHECK(metadata_state IN (\'pending\', \'ready\', \'failed\'))',
      ],
      columns: [
        _column_5,
        _column_6,
        _column_18,
        _column_8,
        _column_9,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 artworkAssets = Shape4(
    source: i0.VersionedTable(
      entityName: 'artwork_assets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['CHECK(byte_length >= 0)'],
      columns: [
        _column_5,
        _column_6,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_16,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 artists = Shape5(
    source: i0.VersionedTable(
      entityName: 'artists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_5,
        _column_6,
        _column_52,
        _column_53,
        _column_54,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 albums = Shape6(
    source: i0.VersionedTable(
      entityName: 'albums',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(release_year IS NULL OR release_year BETWEEN 1 AND 9999)',
      ],
      columns: [
        _column_5,
        _column_6,
        _column_55,
        _column_56,
        _column_54,
        _column_57,
        _column_58,
        _column_59,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 tracks = Shape7(
    source: i0.VersionedTable(
      entityName: 'tracks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(duration_ms IS NULL OR duration_ms >= 0)',
        'CHECK(bitrate_bps IS NULL OR bitrate_bps >= 0)',
        'CHECK(sample_rate_hz IS NULL OR sample_rate_hz > 0)',
        'CHECK(track_number IS NULL OR track_number > 0)',
        'CHECK(track_total IS NULL OR track_total > 0)',
        'CHECK(disc_number IS NULL OR disc_number > 0)',
        'CHECK(disc_total IS NULL OR disc_total > 0)',
        'CHECK(release_year IS NULL OR release_year BETWEEN 1 AND 9999)',
        'CHECK(metadata_revision >= 0)',
      ],
      columns: [
        _column_5,
        _column_6,
        _column_60,
        _column_55,
        _column_56,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_58,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
        _column_59,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 trackArtists = Shape8(
    source: i0.VersionedTable(
      entityName: 'track_artists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(track_id, artist_id, role)',
        'CHECK(position >= 0)',
        'CHECK(role IN (\'primary\', \'performer\'))',
      ],
      columns: [_column_75, _column_76, _column_77, _column_78],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 genres = Shape9(
    source: i0.VersionedTable(
      entityName: 'genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_5,
        _column_6,
        _column_52,
        _column_54,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 trackGenres = Shape10(
    source: i0.VersionedTable(
      entityName: 'track_genres',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(track_id, genre_id)',
        'CHECK(position >= 0)',
      ],
      columns: [_column_75, _column_79, _column_78],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 favoriteTracks = Shape11(
    source: i0.VersionedTable(
      entityName: 'favorite_tracks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(track_id)'],
      columns: [_column_75, _column_16],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 userPlaylists = Shape12(
    source: i0.VersionedTable(
      entityName: 'user_playlists',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(length(trim(name)) > 0)',
        'CHECK(length(trim(normalized_name)) > 0)',
      ],
      columns: [
        _column_5,
        _column_6,
        _column_52,
        _column_80,
        _column_81,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 userPlaylistItems = Shape13(
    source: i0.VersionedTable(
      entityName: 'user_playlist_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'UNIQUE(playlist_id, track_id)',
        'UNIQUE(playlist_id, position)',
        'CHECK(position >= 0)',
      ],
      columns: [_column_5, _column_82, _column_75, _column_78, _column_83],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index mediaFilesRootAvailability = i1.Index(
    'media_files_root_availability',
    'CREATE INDEX media_files_root_availability ON media_files (root_id, availability_state)',
  );
  final i1.Index mediaFilesRootLastSeenGeneration = i1.Index(
    'media_files_root_last_seen_generation',
    'CREATE INDEX media_files_root_last_seen_generation ON media_files (root_id, last_seen_generation)',
  );
  final i1.Index mediaFilesPlatformFileId = i1.Index(
    'media_files_platform_file_id',
    'CREATE INDEX media_files_platform_file_id ON media_files (platform_file_id)',
  );
  final i1.Index mediaFilesQuickFingerprint = i1.Index(
    'media_files_quick_fingerprint',
    'CREATE INDEX media_files_quick_fingerprint ON media_files (quick_fingerprint)',
  );
  final i1.Index mediaFilesContentHash = i1.Index(
    'media_files_content_hash',
    'CREATE INDEX media_files_content_hash ON media_files (content_hash)',
  );
  final i1.Index artistsSortName = i1.Index(
    'artists_sort_name',
    'CREATE INDEX artists_sort_name ON artists (sort_name)',
  );
  final i1.Index artistsName = i1.Index(
    'artists_name',
    'CREATE INDEX artists_name ON artists (name)',
  );
  final i1.Index albumsSortTitle = i1.Index(
    'albums_sort_title',
    'CREATE INDEX albums_sort_title ON albums (sort_title)',
  );
  final i1.Index albumsAlbumArtistId = i1.Index(
    'albums_album_artist_id',
    'CREATE INDEX albums_album_artist_id ON albums (album_artist_id)',
  );
  final i1.Index albumsArtworkId = i1.Index(
    'albums_artwork_id',
    'CREATE INDEX albums_artwork_id ON albums (artwork_id)',
  );
  final i1.Index tracksAlbumId = i1.Index(
    'tracks_album_id',
    'CREATE INDEX tracks_album_id ON tracks (album_id)',
  );
  final i1.Index tracksSortTitle = i1.Index(
    'tracks_sort_title',
    'CREATE INDEX tracks_sort_title ON tracks (sort_title)',
  );
  final i1.Index tracksTitle = i1.Index(
    'tracks_title',
    'CREATE INDEX tracks_title ON tracks (title)',
  );
  final i1.Index tracksArtworkId = i1.Index(
    'tracks_artwork_id',
    'CREATE INDEX tracks_artwork_id ON tracks (artwork_id)',
  );
  final i1.Index trackArtistsArtistRolePosition = i1.Index(
    'track_artists_artist_role_position',
    'CREATE INDEX track_artists_artist_role_position ON track_artists (artist_id, role, position)',
  );
  final i1.Index trackArtistsTrackPosition = i1.Index(
    'track_artists_track_position',
    'CREATE INDEX track_artists_track_position ON track_artists (track_id, position)',
  );
  final i1.Index trackGenresGenreId = i1.Index(
    'track_genres_genre_id',
    'CREATE INDEX track_genres_genre_id ON track_genres (genre_id)',
  );
  final i1.Index trackGenresTrackPosition = i1.Index(
    'track_genres_track_position',
    'CREATE INDEX track_genres_track_position ON track_genres (track_id, position)',
  );
  final i1.Index favoriteTracksCreatedAt = i1.Index(
    'favorite_tracks_created_at',
    'CREATE INDEX favorite_tracks_created_at ON favorite_tracks (created_at, track_id)',
  );
  final i1.Index userPlaylistsUpdatedAt = i1.Index(
    'user_playlists_updated_at',
    'CREATE INDEX user_playlists_updated_at ON user_playlists (updated_at)',
  );
  final i1.Index userPlaylistItemsPlaylistPosition = i1.Index(
    'user_playlist_items_playlist_position',
    'CREATE INDEX user_playlist_items_playlist_position ON user_playlist_items (playlist_id, position)',
  );
}

class Shape0 extends i0.VersionedVirtualTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get trackPublicId =>
      columnsByName['track_public_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get artist =>
      columnsByName['artist']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get album =>
      columnsByName['album']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fileName =>
      columnsByName['file_name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'track_public_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'artist',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'album',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'file_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get rowId =>
      columnsByName['row_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get publicId =>
      columnsByName['public_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceType =>
      columnsByName['source_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get locator =>
      columnsByName['locator']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get locatorKey =>
      columnsByName['locator_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get recursive =>
      columnsByName['recursive']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get enabled =>
      columnsByName['enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scanGeneration =>
      columnsByName['scan_generation']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastScanStartedAt =>
      columnsByName['last_scan_started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastScanCompletedAt =>
      columnsByName['last_scan_completed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'row_id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'public_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'locator',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'locator_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'recursive',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK ("recursive" IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'scan_generation',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_scan_started_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_scan_completed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get rowId =>
      columnsByName['row_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get publicId =>
      columnsByName['public_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get rootId =>
      columnsByName['root_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get generation =>
      columnsByName['generation']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get finishedAt =>
      columnsByName['finished_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get discoveredCount =>
      columnsByName['discovered_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get unchangedCount =>
      columnsByName['unchanged_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get parsedCount =>
      columnsByName['parsed_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get insertedCount =>
      columnsByName['inserted_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedCount =>
      columnsByName['updated_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get missingCount =>
      columnsByName['missing_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get failedCount =>
      columnsByName['failed_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get failureCode =>
      columnsByName['failure_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get failureMessage =>
      columnsByName['failure_message']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'root_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES library_roots(row_id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'generation',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'finished_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'discovered_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'unchanged_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'parsed_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'inserted_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'missing_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'failed_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'failure_code',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'failure_message',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get rowId =>
      columnsByName['row_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get publicId =>
      columnsByName['public_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get rootId =>
      columnsByName['root_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get locator =>
      columnsByName['locator']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get locatorKey =>
      columnsByName['locator_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get relativePath =>
      columnsByName['relative_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fileName =>
      columnsByName['file_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get extension =>
      columnsByName['extension']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sizeBytes =>
      columnsByName['size_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get modifiedAtMicros =>
      columnsByName['modified_at_micros']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get platformFileId =>
      columnsByName['platform_file_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get quickFingerprint =>
      columnsByName['quick_fingerprint']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentHash =>
      columnsByName['content_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get availabilityState =>
      columnsByName['availability_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get metadataState =>
      columnsByName['metadata_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastSeenGeneration =>
      columnsByName['last_seen_generation']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastSeenAt =>
      columnsByName['last_seen_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get missingSince =>
      columnsByName['missing_since']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastErrorCode =>
      columnsByName['last_error_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastErrorMessage =>
      columnsByName['last_error_message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'relative_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'file_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'extension',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'size_bytes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'modified_at_micros',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'platform_file_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'quick_fingerprint',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content_hash',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'availability_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'metadata_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_seen_generation',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_seen_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'missing_since',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_error_code',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_error_message',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get rowId =>
      columnsByName['row_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get publicId =>
      columnsByName['public_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contentHash =>
      columnsByName['content_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mimeType =>
      columnsByName['mime_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get byteLength =>
      columnsByName['byte_length']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get relativeCachePath =>
      columnsByName['relative_cache_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastAccessedAt =>
      columnsByName['last_accessed_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content_hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mime_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'byte_length',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'relative_cache_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_accessed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get rowId =>
      columnsByName['row_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get publicId =>
      columnsByName['public_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sortName =>
      columnsByName['sort_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get identityKey =>
      columnsByName['identity_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sort_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'identity_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get rowId =>
      columnsByName['row_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get publicId =>
      columnsByName['public_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sortTitle =>
      columnsByName['sort_title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get identityKey =>
      columnsByName['identity_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get albumArtistId =>
      columnsByName['album_artist_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get releaseYear =>
      columnsByName['release_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get artworkId =>
      columnsByName['artwork_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sort_title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'album_artist_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES artists(row_id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'release_year',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'artwork_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NULL REFERENCES artwork_assets(row_id)ON DELETE SET NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get rowId =>
      columnsByName['row_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get publicId =>
      columnsByName['public_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get mediaFileId =>
      columnsByName['media_file_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sortTitle =>
      columnsByName['sort_title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayArtist =>
      columnsByName['display_artist']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayAlbum =>
      columnsByName['display_album']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get albumId =>
      columnsByName['album_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bitrateBps =>
      columnsByName['bitrate_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sampleRateHz =>
      columnsByName['sample_rate_hz']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get trackNumber =>
      columnsByName['track_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get trackTotal =>
      columnsByName['track_total']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get discNumber =>
      columnsByName['disc_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get discTotal =>
      columnsByName['disc_total']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get releaseYear =>
      columnsByName['release_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get language =>
      columnsByName['language']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get metadataSource =>
      columnsByName['metadata_source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get metadataRevision =>
      columnsByName['metadata_revision']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get searchText =>
      columnsByName['search_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get artworkId =>
      columnsByName['artwork_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'media_file_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL UNIQUE REFERENCES media_files(row_id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_artist',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_album',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_63(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'album_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES albums(row_id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_65(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'bitrate_bps',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_66(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sample_rate_hz',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'track_number',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_68(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'track_total',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_69(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'disc_number',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_70(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'disc_total',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'language',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_72(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'metadata_source',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_73(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'metadata_revision',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_74(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'search_text',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get trackId =>
      columnsByName['track_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get artistId =>
      columnsByName['artist_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_75(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'track_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES tracks(row_id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_76(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'artist_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES artists(row_id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_77(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'role',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_78(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get rowId =>
      columnsByName['row_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get publicId =>
      columnsByName['public_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get identityKey =>
      columnsByName['identity_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get trackId =>
      columnsByName['track_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get genreId =>
      columnsByName['genre_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_79(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'genre_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES genres(row_id)ON DELETE CASCADE',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get trackId =>
      columnsByName['track_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get rowId =>
      columnsByName['row_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get publicId =>
      columnsByName['public_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get normalizedName =>
      columnsByName['normalized_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_80(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'normalized_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_81(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get rowId =>
      columnsByName['row_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playlistId =>
      columnsByName['playlist_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get trackId =>
      columnsByName['track_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get addedAt =>
      columnsByName['added_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_82(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'playlist_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES user_playlists(row_id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_83(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'added_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
